### ISSUE TITLE
`isExcludedPath` is not a function - null pointer when calling json-schema-ref-parser

### ISSUE THREAD

**Issue by Prescientje** [Rhosys/openapi-model-validator.js#5]
**Describe the bug**
Our applications receive `'isExcludedPath' is not a function` when using this library, because this library provides empty object parameters to the 'dereference' call [here](https://github.com/Rhosys/openapi-data-validator.js/blob/release/2.0/src/index.ts#L84). 
Alternatively, if the import of that method was not done as a direct import, and was instead `const { dereference } = require('@apidevtools/json-schema-ref-parser')` then the json-schema-ref-parser methods would be properly initialized.

**To Reproduce**
1. Use the latest version of this library, and call the loadSpec function.

**Actual behavior** 
1. The call quickly fails before validation can take place with the exception.

**Expected behavior**
1. The call to validate the spec does not throw an exception.

**Comment by wparad** [comment]
Hey, thanks for reporting this, we'll take a look at soon as possible. In the meantime, if you have any suggestions for how to fix this, feel free to put up a PR, and we'll review it.

**Comment by wparad** [comment]
This was actually a bug caused by improper documentation in the dependency and an upgrade to the latest version. Reverting the version upgrade/pinning the version on your side would have fixed this.

In any case we've resolved this problem by providing a default to the `excludedPathMatcher`  which also mimics the fix in the later major version of the dependency (which for some reason they didn't push back to where it broke)

https://github.com/APIDevTools/json-schema-ref-parser/blob/a5b3946fbb62683ab69e3747a8893014591726af/lib/dereference.ts#L62

Thanks again for finding this problem and creating the issue. it is now resolved.
